Revert "Change  SVT_FULL_VERSION"
This reverts commit 1404989dae48e7d3cc174ee60a1ac064d52ac6a2.

The commit broke compilation of src/codec_svt.c:

  libavif/src/codec_svt.c:8:10: fatal error: 'svt-av1/EbVersion.h' file not found
  #include "svt-av1/EbVersion.h"
           ^~~~~~~~~~~~~~~~~~~~~