Work around a bug in the windows-latest os image
The bug causes access violation in avifcodectest when libgav1 is used.
The error message is:
  error: SEH exception with code 0xc0000005 thrown in the test body.