apps:avifpng: Remove unused variable hasAlpha
apps/shared/avifpng.c: In function 'avifPNGRead':
apps/shared/avifpng.c:80:14: error: variable 'hasAlpha' set but not used [-Werror=unused-but-set-variable]
    avifBool hasAlpha = AVIF_FALSE;
             ^~~~~~~~

Signed-off-by: Andreas Schneider <asn@cryptomilk.org>