gdk-pixbuf: Chase 676aded3501f
contrib/gdk-pixbuf/loader.c:212:29: error: no member named 'mode' in 'struct avifImageMirror'
        switch (image->imir.mode) {
                ~~~~~~~~~~~ ^

This reverts commit 0f729c156d7d3fa0aea050908f345d983ba54cbb.