Get ubsan fuzztest test to build.
- add missing flags that would trigger undefined reference to asan
- update fuzztest to not get an undefined reference to LLVMFuzzerRunDriver
- use normal flags for projects built outside of libavif (dav1d with
meson is problematic with sanitizer flags so let's minimize risks)