Fix few compile warnings
 * missing 'static'
 * use (void*) case to work around obscure C rule about 'const ptr**' versus 'ptr**':

avifenc.c:997:86: error: cast from 'avifImage **' (aka 'struct avifImage **') to 'const avifImage **' (aka 'const struct avifImage **')
      must have all intermediate pointers const qualified to be safe [-Werror,-Wcast-qual]
            encoder, (uint8_t)gridDims[0], (uint8_t)gridDims[1], (const avifImage **)gridCells, AVIF_ADD_IMAGE_FLAG_SINGLE);
                                                                                     ^